
title: "Danielle Stevens, PhD"
author: "Danielle Stevens"
description: "Danielle Stevens, PhD"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: About}
#  - {url: "/Danielle R Stevens_CV.pdf", title: CV}
  - {url: "https://scholar.google.com/citations?user=Jb9O26AAAAAJ&hl=en", title: Publications}
  - {file: "fun.md", title: Fun}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:stevensdr99@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/simplydani99"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/simplydani99"}


remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed

